### PR TITLE
implemented dismiss keyboard

### PR DESCRIPTION
**Pull request by JulioC-19**
This PR implements dismiss keyboard functionality for the input fields in sign, login and child create. 

To test:
- Do a fresh install 
- Create a parent and enter some inputs, tab anywhere outside the textInput, the keyboard should hide. 
- Test the same in parent login screen and child create screen. 
- Test the same in forgot password screen.

### CODE REVIEW

**Review by RuthShryock — APPROVED** [review]
Nice, works great!

Can we make the flashcard spin a bit faster like 1000, I feel like 1800 is too slow.

**Comment by RuthShryock** [comment]
looks good

**Review by mackorooji8 — COMMENTED** [review]
Everything looks good except that the flashcards slowed down for me instead of speed up?!

**Comment by JulioC-19** [comment]
@mackorooji8 Yeah I increased duration from 500 ms to 1000 ms

**Review by mackorooji8 — APPROVED** [review]
Oh ok in that case all is well! I was confused because I saw Ruth's comment and was expecting it to spin faster than I was used too, but it did the opposite

**Pull request merged**
