### PR TITLE
Mack/roadmap3&4 fragments

### PR DESCRIPTION
**Pull request by mackorooji8**
Closes issue #146. The only fragments that are left are vertical equation and to fix the division fragment. To test I suppose just run the app and go through each lesson to see the contents are there. Roadmap 2 Lesson 2, Roadmap 2 Lesson 5, and Roadmap 4 Lesson 2 use the vertical equation fragment, so those lessons won't really work. Another key thing to note is that because of some backgrounds being the wrong color, there are many times where an image or text is not easy to see or completely unable to be seen because of the background being the same color as it. Once issue #145 is completed this won't be a problem.

### CODE REVIEW

**Comment by RuthShryock** [comment]
everything looks good, nice work!

**Review by RuthShryock — APPROVED** [review]

**Comment by JulioC-19** [comment]
Could you not commit that .idea folder? I'm not sure why those files are always changing but they seem unique to the local environment.

**Comment by mackorooji8** [comment]
I don't really know exactly how I'm supposed to do what you're asking @JulioC-19. I've tried to figure out how for quite a while now but what I meant to do is delete the files from my pr not actually have the files get deleted in the main branch if this pr gets approved. I also added these files to .gitignore so they don't show up when I want to commit for now on, but that doesn't help with this pr specifically

**Comment by mackorooji8** [comment]
Ok I think I fixed it for the most part now

**Review by JulioC-19 — APPROVED** [review]
Fragments are looking good.

**Pull request merged**
