### PR TITLE
Julio/quiz flashcard tables

### PR DESCRIPTION
**Pull request by JulioC-19**
This PR implements quiz schema, flashcard schema updates lesson schema and roadmap schema. 
 
To test:
Uninstall the app. 
Build and run the app, make sure it does not crash. 
Find the realm file and inspect that the default data for the mentioned schemas are there. 

Note: 
The schema service files still need implemented, will open a ticket for it.

### CODE REVIEW

**Review by mackorooji8 — APPROVED** [review]
Tested it following the instructions provided and there indeed is some data populated under QuizSchema 😃

**Comment by RuthShryock** [comment]
This pr shouldn't be merged until it is updated from main and also see if the bug with the refresh on the main page is fixed.

**Comment by RuthShryock** [comment]
UI bug is gone, works great!

**Comment by mackorooji8** [comment]
reviewed it again, its working 👍

**Pull request merged**
